// app.vue
<template>
    <form @submit.prevent="handleSubmit">
        <label>Nome:</label>
        <input v-model="nome" type="text" required />

        <label>Email:</label>
        <input v-model="email" type="email" required />

        <label>Senha:</label>
        <input v-model="senha" type="password" required />

        <button type="submit">Cadastrar</button>
    </form>
</template>

<script>
export default {
    data() {
        return {
            nome: '',
            email: '',
            senha: '',
        };
    },
    methods: {
        async handleSubmit() {
            try {
                await this.$http.post('http://localhost:3001/cadastro', {
                    nome: this.nome,
                    email: this.email,
                    senha: this.senha,
                });
                alert('Cadastro realizado com sucesso!');
            } catch (error) {
                console.error('Erro ao cadastrar usuário:', error);
            }
        },
    },
};
</script>

// app.jsx
import React, { useState } from 'react';
import axios from 'axios';

const CadastroForm = () => {
    const [nome, setNome] = useState('');
    const [email, setEmail] = useState('');
    const [senha, setSenha] = useState('');

    const handleSubmit = async (e) => {
        e.preventDefault();

        try {
            await axios.post('http://localhost:3001/cadastro', { nome, email, senha });
            alert('Cadastro realizado com sucesso!');
        } catch (error) {
            console.error('Erro ao cadastrar usuário:', error);
        }
    };

    return (
        <form onSubmit={handleSubmit}>
            <label>Nome:</label>
            <input type="text" value={nome} onChange={(e) => setNome(e.target.value)} required />

            <label>Email:</label>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />

            <label>Senha:</label>
            <input type="password" value={senha} onChange={(e) => setSenha(e.target.value)} required />

            <button type="submit">Cadastrar</button>
        </form>
    );
};

export default CadastroForm;
